######################################################################
# Automatically generated by qmake (3.0) Sat Jun 20 11:57:06 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = sa
TEMPLATE = app


SOURCES += \
    mainwindows.cpp \
    main.cpp

HEADERS  += \
    mainwindows.h
